-- ==============================================================================
-- TRIP BANK SUPABASE DATABASE SCHEMA
-- Run this script in your Supabase Project -> SQL Editor -> Click "Run"
-- Project URL: https://jbupkhdchvyyhwapsgln.supabase.co
-- ==============================================================================

-- 1. Table: people (stores trip members)
CREATE TABLE IF NOT EXISTS public.people (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL UNIQUE,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table: expenses (stores all borrows, group spends & personal spends)
CREATE TABLE IF NOT EXISTS public.expenses (
    id TEXT PRIMARY KEY,
    spent_by TEXT NOT NULL,
    amount NUMERIC NOT NULL,
    spent_for JSONB NOT NULL DEFAULT '[]'::jsonb,
    description TEXT DEFAULT '',
    date TEXT DEFAULT '',
    secret_key TEXT DEFAULT '',
    is_borrow BOOLEAN DEFAULT FALSE,
    is_self_spend BOOLEAN DEFAULT FALSE,
    created_at BIGINT DEFAULT 0
);

-- 3. Table: default_all_spends (stores "Add for All" rules applied to future members)
CREATE TABLE IF NOT EXISTS public.default_all_spends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC NOT NULL,
    description TEXT DEFAULT '',
    date TEXT DEFAULT '',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ------------------------------------------------------------------------------
-- Enable Row Level Security (RLS) on each table
-- ------------------------------------------------------------------------------
ALTER TABLE public.people ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.expenses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.default_all_spends ENABLE ROW LEVEL SECURITY;

-- ------------------------------------------------------------------------------
-- Policies: Allow full anonymous access (Select, Insert, Update, Delete) via Anon Key
-- ------------------------------------------------------------------------------
DROP POLICY IF EXISTS "Allow anon all on people" ON public.people;
CREATE POLICY "Allow anon all on people" ON public.people 
    FOR ALL TO anon 
    USING (true) 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on expenses" ON public.expenses;
CREATE POLICY "Allow anon all on expenses" ON public.expenses 
    FOR ALL TO anon 
    USING (true) 
    WITH CHECK (true);

DROP POLICY IF EXISTS "Allow anon all on default_all_spends" ON public.default_all_spends;
CREATE POLICY "Allow anon all on default_all_spends" ON public.default_all_spends 
    FOR ALL TO anon 
    USING (true) 
    WITH CHECK (true);
